project:
  type: website
  output-dir: docs
  
website:
  title: "Giulia Pucci"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/giulia-pucci/
      - icon: envelope
        url: mailto:pucci@kth.se
      - icon: github
        href: https://github.com/giuliapucci98
  
        
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Giulia Pucci"

format:
  html:
    theme: sky
    toc: true

editor: source

